### ISSUE TITLE
traci.exceptions.FatalTraCIError: connection closed by SUMO

### ISSUE THREAD

**Issue by ynuwm** [cts198859/deeprl_signal_control#26]
I train the first model IA2C, another error is occurs, can you help me check it? my sumo version is 1.3.0, should I change the version of sumo?
```p
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    train(args)
  File "main.py", line 131, in train
    trainer.run()
  File "/project/wangmin/Multi-Agent-master/utils.py", line 285, in run
    ob, done, R, cur_rewards = self.explore(ob, done)
  File "/project/wangmin/Multi-Agent-master/utils.py", line 160, in explore
    next_ob, reward, done, global_reward = self.env.step(action)
  File "/project/wangmin/Multi-Agent-master/envs/env.py", line 584, in step
    self._simulate(rest_interval_sec)
  File "/project/wangmin/Multi-Agent-master/envs/env.py", line 474, in _simulate
    self.sim.simulationStep()
  File "/home/wangmin/project/sumo-1_3_0/tools/traci/connection.py", line 319, in simulationStep
    result = self._sendExact()
  File "/home/wangmin/project/sumo-1_3_0/tools/traci/connection.py", line 98, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
```

**Comment by cts198859** [comment]
It seems the Traci port is early terminated by your change in the previous issue. Are you using the system python3.6 on your machine? Can you reinstall tensorflow by using `pip`? If you are using mac or linux/ubuntu machine, try running `setup_mac.sh` or `setup_ubuntu.sh`.

**Comment by ynuwm** [comment]
The server of our school restarted today, and now it is back to normal. I check if this is the reason.

**Comment by ynuwm** [comment]
This is caused by our school shutting down the server, now I can run the program normally.

**Comment by cts198859** [comment]
Cool, I will close this thread then
